serveur: serveur-v3.o
	$(CC) -o serveur serveur-v3.o

serveur-v3.o: serveur-v3.c
	$(CC) -O -Wall -W -ansi -c serveur-v3.c

#################################################################################

clean:
	rm -f *~ *.o
	rm -f serveur