client: client-v2.o
	$(CC) -o client client-v2.o

client-v2.o: client-v2.c
	$(CC) -O -Wall -W -ansi -c client-v2.c

#################################################################################

clean:
	rm -f *~ *.o
	rm -f client