serveur: serveur-v2.o
	$(CC) -o serveur serveur-v2.o

serveur-v2.o: serveur-v2.c
	$(CC) -O -Wall -W -ansi -c serveur-v2.c

#################################################################################

clean:
	rm -f *~ *.o
	rm -f serveur